# Generated by Django 4.2.10 on 2024-03-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(editable=False, max_length=150, verbose_name='Username')),
                ('github_url', models.URLField(editable=False, max_length=250, verbose_name='Github Profile')),
                ('github_thumbnail', models.URLField(editable=False, max_length=250, verbose_name='Github Thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
            ],
            options={
                'verbose_name': 'Github User',
                'verbose_name_plural': 'Github Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
