# Generated by Django 4.2.10 on 2024-03-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyhub_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubuser',
            old_name='github_thumbnail',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='githubuser',
            old_name='github_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='username',
            field=models.CharField(max_length=150, verbose_name='Username'),
        ),
    ]
