# Generated by Django 4.2.10 on 2024-03-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyhub_app', '0002_rename_github_thumbnail_githubuser_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='last_consulted',
            field=models.DateTimeField(auto_now=True, verbose_name='Last checked on'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Username'),
        ),
    ]
