# Generated by Django 4.2.10 on 2024-03-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyhub_app', '0003_githubuser_last_consulted_alter_githubuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='username',
            field=models.CharField(max_length=150, verbose_name='Username'),
        ),
    ]
