# Generated by Django 4.2.10 on 2024-02-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AddField(
            model_name='framework',
            name='is_backend',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Backend?'),
        ),
        migrations.AddField(
            model_name='framework',
            name='is_frontend',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Frontend?'),
        ),
        migrations.AddField(
            model_name='language',
            name='is_backend',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Backend?'),
        ),
        migrations.AddField(
            model_name='language',
            name='is_frontend',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Frontend?'),
        ),
        migrations.AddField(
            model_name='library',
            name='is_backend',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Backend?'),
        ),
        migrations.AddField(
            model_name='library',
            name='is_frontend',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Frontend?'),
        ),
        migrations.AddField(
            model_name='software',
            name='is_backend',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Backend?'),
        ),
        migrations.AddField(
            model_name='software',
            name='is_frontend',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Frontend?'),
        ),
        migrations.AddField(
            model_name='technology',
            name='is_backend',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Backend?'),
        ),
        migrations.AddField(
            model_name='technology',
            name='is_frontend',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Frontend?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Full name'),
        ),
    ]
