# Generated by Django 4.2.10 on 2024-02-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_user_user_framework_is_backend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='is_backend',
        ),
        migrations.RemoveField(
            model_name='software',
            name='is_frontend',
        ),
    ]
