# Generated by Django 4.2.10 on 2024-02-18 21:50

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_software_is_backend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='is_backend',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Backend?'),
        ),
        migrations.AddField(
            model_name='software',
            name='is_frontend',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Frontend?'),
        ),
        migrations.AddField(
            model_name='user',
            name='libraries',
            field=models.ManyToManyField(blank=True, to='website.library', verbose_name='Liked Libraries'),
        ),
        migrations.AddField(
            model_name='user',
            name='softwares',
            field=models.ManyToManyField(blank=True, to='website.software', verbose_name='Liked Softwares'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=website.models.get_image_upload_path, validators=[website.models.validate_image_size])),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.project', verbose_name='Project Images')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
