# Generated by Django 4.2.10 on 2024-02-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_software_is_backend_software_is_frontend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Show this project?'),
        ),
    ]
