# Generated by Django 4.2.10 on 2024-02-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_user_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_public',
        ),
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Show this project?'),
        ),
    ]
