# Generated by Django 4.2.10 on 2024-02-22 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_propertyimage_projectimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='property',
            new_name='project',
        ),
    ]
