# Generated by Django 4.2.10 on 2024-02-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_property_projectimage_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='GitHub Repository'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Project Link'),
        ),
    ]
