# Generated by Django 4.2.10 on 2024-02-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_project_github_url_project_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Portfolio/projectsthumbnails/', verbose_name='Thumbnail'),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100, verbose_name='Institution')),
                ('course', models.CharField(max_length=150, verbose_name='Course name')),
                ('year', models.PositiveIntegerField(verbose_name='Year issued')),
                ('link', models.URLField(max_length=250, verbose_name='Certificate / Course link')),
                ('is_public', models.BooleanField(default=False, verbose_name='Show this project?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('framework', models.ManyToManyField(blank=True, to='website.framework', verbose_name='Used Frameworks')),
                ('languages', models.ManyToManyField(blank=True, to='website.language', verbose_name='Used Languages')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-year'],
            },
        ),
    ]
