# Generated by Django 4.2.10 on 2024-02-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_project_thumbnail_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='libraries',
            field=models.ManyToManyField(blank=True, to='website.library', verbose_name='Used libraries'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Show this certificate?'),
        ),
    ]
