# Generated by Django 4.2.10 on 2024-03-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_framework_certification_frameworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project Link'),
        ),
    ]
